spring:
  #  mvc:
  #      static-path-pattern: /res/**
  web:
    resources:
      add-mappings: true
      cache:
        period: 1234

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#debug: true